document feature flags available
crossplane/docs pull request #402
Opened 2023-04-17 10:46 UTC by phisco

Fixes #397

2023-04-17 14:45 UTC, jeanduplessis approved these changes

2023-04-17 16:39 UTC, plumbis requested changes
Small edits to remove passive voice and `disabled` to pass the Vale checks. 

Thanks for the contribution!

2023-04-17 16:39 UTC, plumbis commented on content/master/software/install.md
> +disable a feature flag, set the `args` value in the Helm chart. Available
```suggestion
turn off a feature flag, set the `args` value in the Helm chart. Available
```

2023-04-17 16:39 UTC, plumbis commented on content/master/software/install.md
> +Crossplane usually introduces new features behind feature flags. Alpha features
```suggestion
Alpha and beta features are behind feature flags. Alpha features
```

2023-04-17 16:39 UTC, plumbis commented on content/master/software/install.md
> +These can be set either in the `values.yaml` file or at install time using the
```suggestion
Set these flags either in the `values.yaml` file or at install time using the
```

2023-04-17 16:41 UTC, plumbis commented
> we might want to consider removing the Vale rule for disabled.

@jeanduplessis I went back and forth on this one, even opening a [PR](https://github.com/crossplane/docs/pull/404) that I closed a few minutes later.

Although I think we can justify our use of the word `disabled` we can just as easily use `turn off`. I'd rather err on the side of inclusive language.

2023-04-17 17:41 UTC, phisco commented on content/master/software/install.md
> +or by looking at the table below.
```suggestion
Crossplane usually introduces new features behind feature flags. By default
alpha features are off, while beta features are enabled. To enable a feature
flag, set the `args` value in the Helm chart. Available feature flags can be
directly found by running `crossplane core start --help`, or by looking at the
table below.
```

2023-04-17 20:43 UTC, jeanduplessis commented
I'm okay with disable = turn off. However, it reads funny when we still use enable. 

So I turn off something and then enable it? That feels wrong.

2023-04-18 02:49 UTC, plumbis commented
> So I turn off something and then enable it? That feels wrong.

@jeanduplessis I agree. Would you support adding a rule suggesting `turn on` instead of `enable`? Any commands that are `--enable` would be exempt.

For example,

"Turn on with `--enable`. Blah is turned off by default"

2023-04-18 07:01 UTC, jeanduplessis commented
@plumbis I'm wondering if we are going too far here. If I take a step back and look at "acceptable" language in engineering, I don't see folks objecting to enable/disable as a language choice in the same way that things like master and whitelist/blacklist are objected to. The rule in Vale also clearly speaks to the subject being a person, not an inanimate/abstract concept. 

It is highly unlikely that we would be talking about people in the context of a disability in our technical documentation. The one area I could imagine it being relevant is in our contribution guidelines to give guidance on making content accessible for those with a disability. 

That said, it's such a small part of the potential use case that I favor disabling the rule and relying on the maintainers of this repo to be vigilant when reviewing PRs.

2023-04-18 07:31 UTC, phisco commented on content/master/software/install.md
> +or by looking at the table below.
pushed this, let me know if there is any other change needed @plumbis

2023-04-18 12:52 UTC, plumbis approved these changes

2023-04-18 12:53 UTC, merged