docs: suggest using image digests for security reasons
crossplane/docs pull request #465
Opened 2023-06-13 10:49 UTC by phisco

Suggesting to use image digests instead of tags for security reasons.
This is due to the underlying implementation of go-containerregistry we use to pull images, which is not able to validate digests if not provided, see the [code](https://github.com/google/go-containerregistry/blob/5fe7f2e11795fcfd5a7c7d3a550c4e668a9a9789/pkg/v1/remote/fetcher.go#L172-L180) for more details.
I didn't specifically point out the details, as I feel it's kind of well known in the field that specifying digests is a good practice and a requirement in highly regulated and security-aware environments.

2023-06-20 04:49 UTC, jeanduplessis requested changes
@phisco please would you address the Vale error on line 336 of the files.

2023-06-20 04:49 UTC, jeanduplessis commented on content/master/concepts/packages.md
> +tags (`vx.y.z@sha256:...`), to ensure that the package content was not tampered
```suggestion
tags (`vx.y.z@sha256:...`), to ensure that the package content wasn't tampered
```

2023-06-20 04:49 UTC, jeanduplessis commented on content/v1.10/concepts/packages.md
> +tags (`vx.y.z@sha256:...`), to ensure that the package content was not tampered
```suggestion
tags (`vx.y.z@sha256:...`), to ensure that the package content wasn't tampered
```

2023-06-20 04:49 UTC, jeanduplessis commented on content/v1.11/concepts/packages.md
> +tags (`vx.y.z@sha256:...`), to ensure that the package content was not tampered
```suggestion
tags (`vx.y.z@sha256:...`), to ensure that the package content wasn't tampered
```

2023-06-20 04:49 UTC, jeanduplessis commented on content/v1.12/concepts/packages.md
> +tags (`vx.y.z@sha256:...`), to ensure that the package content was not tampered
```suggestion
tags (`vx.y.z@sha256:...`), to ensure that the package content wasn't tampered
```

2023-06-20 05:29 UTC, phisco commented
I tried understanding if there were errors in the lines I changed, but evidently my brain refuses to see "was not" as an actual error. Thanks @jeanduplessis .

Please hold on from merging this though, as I want a check from @AdamKorcz .

2023-06-22 16:26 UTC, AdamKorcz approved these changes
LGTM

2023-06-22 16:37 UTC, phisco commented
@plumbis can you merge this? looks like I can't dismiss the requested changes by @jeanduplessis (which were actually accepted and marked as resolved 🤔)

2023-06-22 16:42 UTC, merged