Update GCP and AWS Quickstarts to no-fork providers
crossplane/docs pull request #661
Opened 2023-12-15 17:29 UTC by plumbis

Updates the AWS quickstart to v0.46.0 and GCP to v0.40.0.

2024-01-01 16:02 UTC, jeanduplessis requested changes

2024-01-01 16:02 UTC, jeanduplessis commented on content/v1.14/getting-started/provider-aws.md
> +[Upbound Marketplace](https://marketplace.upbound.io/providers/upbound/provider-aws-s3/v0.46.0).
```suggestion
[Upbound Marketplace](https://marketplace.upbound.io/providers/upbound/provider-aws-s3/v0.47.0).
```

2024-01-01 16:02 UTC, jeanduplessis commented on content/v1.14/getting-started/provider-gcp-part-2.md
> +  package: xpkg.upbound.io/upbound/provider-gcp-storage:v0.40.0
```suggestion
  package: xpkg.upbound.io/upbound/provider-gcp-storage:v0.41.0
```

2024-01-01 16:02 UTC, jeanduplessis commented on content/v1.14/getting-started/provider-gcp-part-2.md
> +  package: xpkg.upbound.io/upbound/provider-gcp-pubsub:v0.40.0
```suggestion
  package: xpkg.upbound.io/upbound/provider-gcp-pubsub:v0.41.0
```

2024-01-01 16:02 UTC, jeanduplessis commented on content/v1.14/getting-started/provider-gcp-part-2.md
> +upbound-provider-family-gcp   True        True      xpkg.upbound.io/upbound/provider-family-gcp:v0.40.0    12m
```suggestion
provider-gcp-pubsub           True        True      xpkg.upbound.io/upbound/provider-gcp-pubsub:v0.41.0    39s
provider-gcp-storage          True        True      xpkg.upbound.io/upbound/provider-gcp-storage:v0.41.0   13m
upbound-provider-family-gcp   True        True      xpkg.upbound.io/upbound/provider-family-gcp:v0.41.0    12m
```

2024-01-01 16:02 UTC, jeanduplessis commented on content/v1.14/getting-started/provider-gcp.md
> +  package: xpkg.upbound.io/upbound/provider-gcp-storage:v0.40.0
```suggestion
  package: xpkg.upbound.io/upbound/provider-gcp-storage:v0.41.0
```

2024-01-01 16:02 UTC, jeanduplessis commented on content/v1.14/getting-started/provider-gcp.md
> +upbound-provider-family-gcp   True        True      xpkg.upbound.io/upbound/provider-family-gcp:v0.40.0    29s
```suggestion
provider-gcp-storage          True        True      xpkg.upbound.io/upbound/provider-gcp-storage:v0.41.0   36s
upbound-provider-family-gcp   True        True      xpkg.upbound.io/upbound/provider-family-gcp:v0.41.0    29s
```

2024-01-01 16:03 UTC, jeanduplessis commented
@plumbis bumped the version to the latest version in the suggestions.

Is it possible to control these with a variable in Hugo?

2024-01-01 16:08 UTC, plumbis commented
We could but my concern is QA. I would rather have a slightly out of date provider version than have a user's first experience not work due to an oversight or behavior change on our part.

2024-01-01 19:01 UTC, jeanduplessis commented
That's a reasonable consideration. We'll stick to manual updates until it becomes a real problem.

2024-01-02 15:17 UTC, plumbis commented
Pushed a change with the provider version bump.

2024-01-02 15:33 UTC, jeanduplessis approved these changes

2024-01-02 15:33 UTC, merged