Add '--include-full-xr' flag to the render subcommand
crossplane/docs pull request #695
Opened 2024-02-02 13:58 UTC by ezgidemirel

Documents the new render flag `--include-full-xr`.

2024-02-05 18:05 UTC, plumbis requested changes

2024-02-05 18:05 UTC, plumbis commented on content/master/cli/command-reference.md
> +| `-x`         | `--include-full-xr`          | Include a direct copy of the input XR's spec and metadata fields in the rendered output.   |
```suggestion
| `-x`         | `--include-full-xr`          | Include a copy of the input Composite Resource spec and metadata fields in the rendered output.   |
```

2024-02-05 18:05 UTC, plumbis commented on content/master/cli/command-reference.md
> +and `metadata` fields.
```suggestion
#### Include the composite resource 

Composition functions can only change the `status` field of a composite 
resource. By default, the `crossplane beta render` command only prints the
`status` field with `metadata.name`.  

Use `--include-full-xr` to print the full composite resource, 
including the `spec` and `metadata` fields.
```
Suggestions to appease our lord and savior Vale 😆

2024-02-06 01:02 UTC, plumbis commented
Resolves #683

2024-02-14 09:53 UTC, phisco approved these changes

2024-02-14 09:55 UTC, phisco commented
obviously committing from the GUI breaks the DCO 😭 I can't force push on this PR, so I'll just open another PR with the same changes

2024-02-14 10:01 UTC, closed without merging